### PR TITLE
Implement Graylog logo, update sidebar colors and automatically update current year in copyright. (3.0)

### PR DESCRIPTION
**Pull request by linuspahl**
## Description

This PR implements the Graylog logo for the sidebar and updates the sidebar colors by using corporate colors. It also adjusts the config file to update the current year in the copyright info automatically.
image

### CODE REVIEW

**Comment by jalogisch** [comment]
after https://github.com/Graylog2/documentation/pull/1077 is merged the requirements.txt need to be backported to the older version to make this changes work.

**Comment by asachs01** [comment]
@linuspahl or @dulanism was there anything here that you need Support's assistance on?

**Comment by danotorrey** [comment]
@linuspahl Is there any remaining tasks needed to merge this?

**Comment by linuspahl** [comment]
@danotorrey We need to do some maintenance for the 3.0 documentation before we can merge this PR. Dulani can take care of it in the future, but needs to take care of some other topics with a higher priority first.

I am closing this PR for now, we can reopen it, once we've finished the maintenance.

**Pull request closed without merging**
