### PR TITLE
Fixing docs

### PR DESCRIPTION
**Pull request by Fl4m3Ph03n1x**
- Fixed grammar error in index_model.rst
 - Fixed wrong extractors documentation where dot notation is still being used ( https://community.graylog.org/t/documentation-for-extractors-wrong/5369 )
 - Added CSV generation warning

### CODE REVIEW

**Comment by jalogisch** [comment]
LGTM - please fix the author of the commits and after that I would be able to merge your changes.

https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

**Comment by Fl4m3Ph03n1x** [comment]
I have updated the user.name and user.email of the commits I did. Everything should be fine now, but the automatic system doesn't seem to pick it up. 

There is a chance I missed something, but at this point I haveno idea what it could be. 

If the quality of my fixes is good enough, is there a way to accept them and bypass the automatic system?

It is my belief that the longer we wait to fix them, the more users will be confused.

**Review by jalogisch — APPROVED** [review]

**Comment by jalogisch** [comment]
thank you @Fl4m3Ph03n1x

**Comment by jalogisch** [comment]
Just to have it clear - your current PR only contains changes in pages/extractors.rst - you might want to make your other changes also in a new PR? @Fl4m3Ph03n1x

**Comment by Fl4m3Ph03n1x** [comment]
Ahh, my other requests have already been pushed. Looks like I had an issue with my clone ( it was not updated apparently ).

Everything is as it should be. All my PR's have been accepted, merged and pushed.

I hope my contribution is able to help more people in the future and hopefully take some heat of you guys in the forums.

**Pull request merged**
