### PR TITLE
added Information about securing

### PR DESCRIPTION
**Pull request by jalogisch**
Added some notes about secure connection between Sidecar and Graylog and the collectors and Graylog

### CODE REVIEW

**Comment by jalogisch** [comment]
@mariussturm can you please check on that and write your comments.

**Comment by mariussturm** [comment]
Sounds good, thanks!

**Comment by mchubby** [comment]
Might be noteworthy to note you cannot mix secure and unsecure communications on a given Beats Input (IIRC).

**Comment by mariussturm** [comment]
@mchubby I can't think of another protocol that is able to do so but you can create a PR if you think that is helpful.

**Comment by joschi** [comment]
@mariussturm Think `STARTTLS` in SMTP or IMAPv4.

**Pull request merged**
