### PR TITLE
Update collector sidecar documentation

### PR DESCRIPTION
**Pull request by kyrogue**
The provided example configuration is not valid for a windows configuration

### CODE REVIEW

**Comment by kyrogue** [comment]
can someone confirm the line 

> collector_id: file:C:\Program Files\graylog\collector-sidecar\collector-id

actually takes has a 'file' value infront of the path?

**Comment by mariussturm** [comment]
Hi,
you need double slashes for `collector_id`. It's in the format like:
```
collector_id: "file:C:\\Program Files\\graylog\\collector-sidecar\\collector-id
```
Additionally the `list_log_files` option need to be changed for windows.

**Comment by kyrogue** [comment]
Running the graylog_collector installer.exe in windows server 2012, generates what i pasted as the default configuration settings. Or do you mean i need to double slash it to escape the slash in markdown?
What could be a reasonable example to display for the list_log_files directory for windows?

**Comment by mariussturm** [comment]
Ah ok, guess both formats are fine then.
Either you set `list_log_files` to an empty list to disable it or to something like `C:\Windows\System32\winevt\Logs` to see activity on the different event channels. But the unix path doesn't make sense on windows.

**Review by mariussturm — APPROVED** [review]

**Pull request merged**
