### PR TITLE
Add documentation for the debug() function

### PR DESCRIPTION
**Pull request by joschi**
Refs Graylog2/graylog-plugin-pipeline-processor#188

### CODE REVIEW

**Comment by joschi** [comment]
This PR has to be merged into the `2.4` and `3.0` branches, too.

**Comment by jalogisch** [comment]
shouldn't we add on example? 

Cause something like: ` debug( concat("dropped message from ", to_string($message.source)) );` is not very easy to reach without deeper knowledge.

Or would you see that in a FAQ?

**Comment by joschi** [comment]
@jalogisch I left out the example for consistency, as no other function has an example with it.

This being said, I think you're right and users will profit from a specific example in this case.

**Review by jalogisch — APPROVED** [review]
LGTM

**Pull request merged**
