### PR TITLE
added api and api token

### PR DESCRIPTION
**Pull request by jalogisch**
added a general description of the API and how to start to gain knowledge about.

also added how to generate a token, list and delete this token. And how to use....

CLOSE https://github.com/Graylog2/documentation/issues/152
CLOSE https://github.com/Graylog2/documentation/issues/64
CLOSE https://github.com/Graylog2/documentation/issues/203

### CODE REVIEW

**Comment by jalogisch** [comment]
LGTM 👍

**Comment by joschi** [comment]
I don't see how this PR closes #64 or #203, so I've reopened them.

**Comment by jalogisch** [comment]
IMHO this closed #203 as we have something to start with the REST API and this was my intention with #203

**Comment by joschi** [comment]
@jalogisch The original author #203 expected to find an offline version of the Graylog REST API documentation which doesn't rely on a running Graylog instance (i. e. the API browser).

**Pull request merged**
