### PR TITLE
Adjustments to Integrations documentation

### PR DESCRIPTION
**Pull request by danotorrey**
A few adjustments/enhancement to Enterprise Integrations documentation:

- [*] Move Integrations section to Enterprise > Integrations
- [*] Add setup instructions (for new `graylog-plugin-enterprise-integrations`)
- [*] Improve organization

### CODE REVIEW

**Review by jalogisch — CHANGES_REQUESTED** [review]
I would like to have the installation of the package also included in the integrations "sub-section" and not in the general enterprise installation.

Currently, that might make sense - but when we have additional parts that are OSS we should have that all together bundled and not spread over all places.

**Comment by danotorrey** [comment]
This PR is on hold due to some in progress discussions about how to handle open source vs. enterprise integrations

**Comment by danotorrey** [comment]
Hey @jalogisch 
I have made an effort to finish up this documentation, but I need your help to resolve a `WARNING: document isn't included in any toctree` error. I am pretty sure this has to do with the way I have restructured the docs. 

We have moved the Palo Alto input to open source, so I have reworked the Integrations documentation a bit. Most notably, I moved the Integrations documentation out of the Enterprise section, since it's not just for Enterprise now. 

I am very much looking for your expert feedback on this. I am pretty sure the way I have done it is sub-optimal. Tomorrow is my last day in before vacation, so if you have a bit of time to look at this, that would really help, so we can get this merged. Feel free to make any edits that you see appropriate. Thanks so much.

**Comment by jalogisch** [comment]
He @danotorrey please see my commit https://github.com/Graylog2/documentation/pull/514/commits/806b35773362a05de726fb26ed560629881d3ba4 and the comments how I fixed the issues. 

In addition I propose the changed path mentioned in the commit message.

**Review by jalogisch — DISMISSED** [review]

**Comment by danotorrey** [comment]
Made some final adjustments, and the look good to me. I am going to merge this now.

**Pull request merged**
