### PR TITLE
it's --> its

### PR DESCRIPTION
**Pull request by battey**

### CODE REVIEW

**Comment by dennisoelkers** [comment]
@battey: Thank you for the contribution! Unfortunately your commit does not contain the email adress of your github account. You need to fix that and push it again (to the same branch, so you do not need to create a new PR) to be able to sign the CLA so we can merge it. Thanks!

**Comment by edmundoa** [comment]
Hi @battey,
Could you please fix the issue mentioned above so that we can merge this? Otherwise we will have to close the PR.
Thank you!

**Comment by battey** [comment]
I added the email account to my github account, and pushed a new commit. Should be good to go now.

**Review by mpfz0r — APPROVED** [review]

**Comment by mpfz0r** [comment]
Thank you!

**Pull request merged**
