### PR TITLE
Fixing typos and closing issue #2918

### PR DESCRIPTION
**Pull request by Fl4m3Ph03n1x**
Fixed a typo in the index set description. 
Adding needed change to close issue: https://github.com/Graylog2/graylog2-server/issues/2918

### CODE REVIEW

**Comment by Fl4m3Ph03n1x** [comment]
Well, this is both annoying and frustrating. 
I did the commits an the PR. I also pass the Travis tests. 

Buuut ..... The CLAssistant won't accept my PR, even though **I have accepted the terms and conditions** of the License Agreement. 

I have also asked the service to recheck it multiple times but the answer is always the same. 
I can also tell you that I most definetly am Pedro Miguel Pereira Serrano Martins and that I do have a Github account, which is this one ...

**Comment by joschi** [comment]
@Fl4m3Ph03n1x The problem is that the email addresses used in your commits is not the same that you've added to GitHub, so CLAassistant is unable to identify your GitHub user.

> **Pedro Miguel Pereira Serrano Martins** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Review by joschi — APPROVED** [review]
@Fl4m3Ph03n1x LGTM. Thanks!

**Comment by Fl4m3Ph03n1x** [comment]
> @Fl4m3Ph03n1x The problem is that the email addresses used in your commits is not the same that you've added to GitHub, so CLAassistant is unable to identify your GitHub user.

Ahh ... I take it my IDE is miss configured, so the CLAssistant thinks my e-mail is "Pedro Miguel .... ". 
Should be good now, thanks for approving. 

On a separate note, I would like to *dedicate* this PR to you. 

I know I am annoying at times and that you dedicate quite a hefty amount of time helping me and that you even feel frustrated. All normal things when helping beginners. 

But I want you to know I value your help and that if given the chance I also want o *help you*. 
If anything, now you can close an issue. Hopefully people will also stop spamming the forums with this.

Overall, everyone wins. And all because you have enough patience to read my posts. Funny world, right?

**Comment by joschi** [comment]
@Fl4m3Ph03n1x Thanks! 😊

**Comment by bkgilbride** [comment]
Hi @Fl4m3Ph03n1x,

In your documentation edit, you mention:

> If you need to have the exported data ordered you will need to either make a scroll query to ElasticSearch and process it after, or to download the file and post process it via other means.

I am reading that ElasticSearch scroll link, but I am still confused about how a scroll query could be added to sort the exported CSV before downloading. Would you be able to provide more detail?

**Pull request merged**
