### PR TITLE
added default file location

### PR DESCRIPTION
**Pull request by jalogisch**
this includes the first version of file locations

Close: https://github.com/Graylog2/documentation/issues/137

### CODE REVIEW

**Comment by edmundoa** [comment]
It looks like there are other changes in there too, including some merge commits. Was that intended? I want to be sure before we click the button :)

**Comment by jalogisch** [comment]
my tool sucked up my branch ... just cherry-pick my commits.

**Comment by joschi** [comment]
@jalogisch Which commits specifically?

You could also cherry-pick your own commits locally into a new branch and force-push it over `origin/default_file_location`.

**Comment by jalogisch** [comment]
thank you @joschi pointing me and take of the fear how to fix my local branches

**Pull request merged**
